{% set name = "saspy" %}
{% set version = "5.102.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e9bfaeb39ae025df1d99dcef1ae2750ea4d5b6b01e2de467fec3c548870d42c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    # Keep pandas at runtime and don't break the user experience.
    - pandas

test:
  imports:
    - saspy
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/sassoftware/saspy
  license: Apache-2.0 and LicenseRef-SASLicenseAgreement
  license_family: Apache
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: A Python interface module to the SAS System
  description: |
      This module allows a python process to connect to SAS 9.4 and run SAS
      code, generated by the supplied object and methods or explicitly user
      written, and returns results as text, HTML5 documents (via SAS ODS), or
      as Pandas Data Frames. It supports running analytics and returning the
      resulting graphics and result data. It can convert between SAS Data Sets
      and Pandas Data Frames. It has multiple access methods which allow it to
      connect to local or remote Linux SAS, IOM SAS on Windows or Linux
      (Including Grid Manager), and local PC SAS. It can run w/in Jupyter
      Notebooks, in line mode python or in python batch scripts.
  dev_url: https://github.com/sassoftware/saspy
  doc_url: https://sassoftware.github.io/saspy

extra:
  recipe-maintainers:
    - danielfrg
