{% set name = "saspy" %}
{% set version = "3.1.0" %}
{% set hash_type = "sha256" %}
{% set hash_val = "5bc04ff2568f239667a65f782b40589bc11b7a490b8c5713c9b88dd0d410a5b1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python >=3
    - setuptools
    - pip
  run:
    - python >=3
    - ipython >=4
    - pygments
    - pandas

test:
  imports:
    - saspy

about:
  home: https://github.com/sassoftware/saspy
  license: Apache 2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: A Python interface module to the SAS System
  description: |
      This module allows a python process to connect to SAS 9.4 and run SAS
      code, generated by the supplied object and methods or explicitly user
      written, and returns results as text, HTML5 documents (via SAS ODS), or
      as Pandas Data Frames. It supports running analytics and returning the
      resulting graphics and result data. It can convert between SAS Data Sets
      and Pandas Data Frames. It has multiple access methods which allow it to
      connect to local or remote Linux SAS, IOM SAS on Windows or Linux
      (Including Grid Manager), and local PC SAS. It can run w/in Jupyter
      Notebooks, in line mode python or in python batch scripts.
  dev_url: https://github.com/sassoftware/saspy
  doc_url: https://sassoftware.github.io/saspy

extra:
  recipe-maintainers:
    - danielfrg
