travis:
  secure:
    BINSTAR_TOKEN: MKTqp6b/L+txriuJ1VPM6l3ZaDSeVHPfs9Dyn49lCQFXxSv4igaw8hTMdyPqua+hdQkHYuxCRViSEr8xCakLh9zSAEfMCmUkCu2nek2Nn9UvzdvZMQYliVB1luEXyXkMK8ZP5twlt0gSBjbsQxyjteeq+SwXa5F8UFYp0fZJ/VGVSSAWzUT/AZWnvrWdLKAA8JtgPwLfhyH9hiQXfsb69V5X6JMp8NbJzqfz1n9joVSPmNPi+eajCGZb9QzYCYlHaZy4n9v8LSOm/vvyUTMfCqcR2MIC4ZJ03sMGJ6ip7kT7p9gu0HHq7+CA0vf+ot+YfvwJGS1jbNc4WBubfv0D/2oAnlJpEK1mbZFKLwE6G47GpZn6JlGEpWDkLVDb71x7F1ubyttVLI4IOhV7usF0VaO3TEz1SW7l7FKhfBfvNDAv+gvNFZ/G0crDlRiwvwfdBIBSpHmQR0eYyPec/lpZ1sHqjID1IKMB3JzGCbO3yl5FEU618pg9AJz4NcbH4IznyEvSLuByLAorlAavzD1vvjPXSD0eM9emW4TG8T7AgwLWys5842EmaFbgMTgO5NP04sPPO3PMWM1AyoKVQI/oGxmFdcyOc+SeZ0cfnBAN9jTz8yJY2gRG8d3KEDj7jtx56NZglAqZYFSZjcCuPjZL4DaQnLZwstSdMOJgB4TyDw4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
