travis:
  secure:
    BINSTAR_TOKEN: hHA/6Dc0QcIEd297isVZVxWh5TboDMMrarOwhz64WYjDgXerYLm7ywclMHXS22QgvwOXqmcF/eo7IR48HSueOkt8zsbPBBlVlMgAU3V1SqtyNJ3ojUpaACMMpf9TgV+ROFlCWz5Urlf1S1nrRvGiYIL0o90s0xJ51I+8SgOUZ+mK+UrtjGWlLPsuIizVyJyHJq/+mYHnp7/08YB0kQPe8mrrgzhiS30RTJIp9z9XhxrZHB+GI10RPe0bhFkyRsA/XC82TJS7FPOy/5rocVKvmdcjjfR0vqZcspBiN/PgMQ/1EMvmEjxPIziUo1eIEiK/FbblXWTbtCLJIL5md4JpCLGT6o+vrffKL7yMH4gVJDketrcCFsoHJRWEUMwH6i+LbCw7BM19erGHIzR/8DtRkbLqEdl77VWzBOurUQIAwgW+9mBkskJuvRHVKKNiNhOpalwCbHfOMhTsS3PLfxSeeM+GgCjdZpl6glsOE2KagegbraOgSu3MCz1OvQuzZ3NodwdHSMNctfZc0Zad3Dk1EE/RxH8AJYS3J68Ew8msdqadfcO8gLi0TJV9IjKPObzEPfyXoAw8+Fz28F0lmczIpRsLLEUJ9eLhltHNt94M/GafvVfn9dieDTKtQli/E2p4YhcMG6bcuKablO2yfb3oCKodjZrMny1VoZNEErRkjU8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
